name: Update TMDB Movies

on:
  schedule:
    # 每天北京时间 10:00
    - cron: "0 2 * * *"

  workflow_dispatch:

permissions:
  contents: write


jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Fetch TMDB Movies
        env:
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}

        run: |

          python3 << 'EOF'

          import requests
          import json


          TOKEN = "${TMDB_TOKEN}"


          headers = {
              "Authorization": f"Bearer {TOKEN}",
              "accept": "application/json"
          }


          movies = []


          urls = [

          "https://api.themoviedb.org/3/trending/movie/week?language=zh-CN&page=1",

          "https://api.themoviedb.org/3/movie/popular?language=zh-CN&page=1",

          "https://api.themoviedb.org/3/movie/popular?language=zh-CN&page=2",

          "https://api.themoviedb.org/3/movie/top_rated?language=zh-CN&page=1",

          "https://api.themoviedb.org/3/movie/top_rated?language=zh-CN&page=2"

          ]


          for url in urls:

              r = requests.get(
                  url,
                  headers=headers
              )

              data = r.json()


              for item in data.get("results", []):

                  title = (
                      item.get("title")
                      or
                      item.get("name")
                  )

                  if title:
                      movies.append(title)



          # 去重

          movies = list(dict.fromkeys(movies))


          # 保存

          with open(
              "movies.json",
              "w",
              encoding="utf-8"
          ) as f:

              json.dump(
                  movies,
                  f,
                  ensure_ascii=False,
                  indent=2
              )


          print(
              "Movies:",
              len(movies)
          )


          EOF



      - name: Commit changes

        run: |

          git config user.name github-actions

          git config user.email github-actions@github.com


          git add movies.json


          git commit -m "Update movies database" || exit 0


          git push
